### ISSUE TITLE
Error when plugin tries to create temporary directory

### ISSUE THREAD

**Issue by jvdkwast** [ChrisLisbon/QGIS_LinesRankingPlugin#4]
The plugin tries to create a temporary directory on my D drive when I execute the tool. This results in the error below. My D drive is write protected (it's the memory of my port replicator) and shouldn't be used. Would it be possible to use the TEMP or TMP variable that QGIS uses instead?

The error is:
2024-12-29T15:23:18     WARNING    Traceback (most recent call last):
              File "C:\Users/jvdkw/AppData/Roaming/QGIS/QGIS3\profiles\UdemyHydrology/python/plugins\lines_ranking\lines_ranking.py", line 336, in add_task
              self.m.StartScriptTask()
              File "C:\Users/jvdkw/AppData/Roaming/QGIS/QGIS3\profiles\UdemyHydrology/python/plugins\lines_ranking\worker_class.py", line 417, in StartScriptTask
              self.task = StartScript('Lines Ranking processing', QgsTask.CanCancel,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/jvdkw/AppData/Roaming/QGIS/QGIS3\profiles\UdemyHydrology/python/plugins\lines_ranking\worker_class.py", line 58, in __init__
              self.create_base_directory_if_required()
              File "C:\Users/jvdkw/AppData/Roaming/QGIS/QGIS3\profiles\UdemyHydrology/python/plugins\lines_ranking\worker_class.py", line 73, in create_base_directory_if_required
              os.mkdir(self.base_dir)
             PermissionError: [WinError 19] The media is write protected: 'D:lines_ranking_tmp_directory'

**Comment by Dreamlone** [comment]
Hello, thank you for reporting!

I think the similar issue is mentioned in documentation page:
https://linesranking.readthedocs.io/en/latest/usage/troubleshooting/#action-plan-if-plugin-does-not-produce-result. See `Action plan if plugin does not produce result` item `3`. Partly because of this issue, the [plugin tries to avoid creating a directory on the C drive](https://github.com/ChrisLisbon/QGIS_LinesRankingPlugin/blob/master/worker_class.py#L50). 

I agree that a better implementation is to use native QGIS constants. I will try to check how this can be added in the plugin. 

**The question from my side:** were you able to run the plugin or is the current issue blocking you from doing so?

For now, as a temporary solution, I can suggest you to try to save the current project in a specifically selected folder (if you haven't already done so), for example `D:/plugin_testing` and run the plugin from the saved project (`D:/plugin_testing/project.qgz`). Then the temporary directory should appear in the same place where the project file is saved (at least as far as I remember).

**Comment by jvdkwast** [comment]
It's still not working, same error. It seems it always wants to save to my D-drive, which it can't and it shouldn't.
My setup:

- C-drive with system files.
- D-drive reserved for port replicator memory
- Z-drive for my data

I've tested the following:
- Project saved in a GeoPackage on my Z-drive: result of my initial issue posted here.
- Project saved as a .qgz file in a dedicated folder on my Z-drive: same error.
- Project saved as a .qgz file in a dedicated writable folder on my C-drive: same error.

OS: Windows 11
QGIS 3.34.14

**Comment by Dreamlone** [comment]
Got it. 

I tried to apply hotfix via tempfile. Please install plugin from zip archive below and let me know the result. I will prepare a proper release later (when I will be sure in the solution)

[lines_ranking-2.4.2.zip](https://github.com/user-attachments/files/18286510/lines_ranking-2.4.2.zip)

**Comment by jvdkwast** [comment]
Thanks for the fix. It now works great!
